### ISSUE TITLE
No way to change or set profile picture after Github removed Gravatar support

### ISSUE THREAD

**Issue by mklim** [filearts/plunker_api#1]
Github still stores Gravatar IDs for users, but no longer provides any way to change them (Github switched to their own profile picture upload a few weeks ago and dropped Gravatar support). Plunker pulls the Gravatar ID from Github and sets that as the user icon on every login. The icon isn't even necessarily associated with the user's current Github email, it's just whatever the user had set before Github removed Gravatar support.

I'm not sure if this fits www or the api repo better (seems like it affects both, depending on the fix). The most complete fix would be to add a form on the user page that allows users to set their Gravatar email manually. But a partial and simpler way to address it would be to calculate the Gravatar hash in the sessions resource based on that user's primary Github email, instead of just pulling whatever Github has stored (it looks like it'd be a [one line change](https://github.com/filearts/plunker_api/blob/062ab79ea33408b0480906872c5b428033009a46/resources/sessions.coffee#L106), plus a function to calculate the Gravatar hash from an email). At least that way the icon is guaranteed to be tied to their current Github email.

**Comment by cruz210** [comment]
Master can u fork for me and hep me out

**Comment by CBuntrock** [comment]
same issue here

**Comment by d1820** [comment]
Still an issue

**Comment by ggoodman** [comment]
Hi @mklim, @cruz210, @CBuntrock, @d1820 this repository will be deprecated in the near future. Plunker will no longer be relying on gravatar ids coming from Github.
